### ISSUE TITLE
Implement UnicodeSegementation for FromIterator<char>

### ISSUE THREAD

**Issue by oshaboy** [unicode-rs/unicode-segmentation#142]
I'm trying to create a wrapper around UnicodeSegmentation but I hit a snag because UnicodeSegmentation isn't implemented for FromIterator<char>. Way more flexible than just implementing it for &str and probably already done internally.

**Comment by Manishearth** [comment]
A blanket impl would forbid future impls, and the code is internally written over strings because some things require lookbehind.

Use the cursor types if you want to work with an iterator.

https://docs.rs/unicode-segmentation/latest/unicode_segmentation/struct.GraphemeCursor.html

I would be open to accepting an IteratorCursor type built out of GraphemeCursor if it can be a simple implementation.

**Comment by oshaboy** [comment]
I see now that Graphemes uses &str internally as opposed to char I was confusing it for unicode-normalization. So yes that would require a from scratch reimplementation. 

I am not sure you can even build an IteratorCursor over GraphemeCursor without collecting the char iterator. Unless you extend GraphemeCursor to accept arbitrary char iterators as chunks.
